AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Move S3 file file
Resources:
  lambdamovefile:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Move S3 file file
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::474187235891:role/lambda-move-file-executor'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: csv
  Bucket1:
    Type: 'AWS::S3::Bucket'
